spring:
  application:
    name: BBB Predict Bot

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: info
    br.com.luiz.bbbpredict.infra.exception.GlobalExceptionHandler: ERROR

twitter:
  api:
    key: ${TWITTER_API_KEY}
    secret: ${TWITTER_API_SECRET}
  access:
    token: ${TWITTER_ACCESS_TOKEN}
    secret: ${TWITTER_ACCESS_SECRET}

  output:
    ansi:
      enabled: always

